name: Prevent Pull Requests to Master

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Fail if targeting master
      run: |
        echo "This pull request is targeting the 'master' branch. Please change it to 'develop'."
        exit 1
